kb-dk/ds-storage

- src/main/java/dk/kb/storage/facade/DsStorageFacade.java
This decouples transaction and exception handling from core logic
> Refactor DsStorageFacade

- src/main/java/dk/kb/storage/api/v1/impl/DsStorageApiServiceImpl.java
- src/main/openapi/openapi_ds-storage_v1.yaml
Tiny PR containing ping endpoint
> Add ping endpoint

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/dk/kb/storage/util/DsStorageClient.java
- src/test/java/dk/kb/storage/util/DsStorageClientTest.java
Same procedure as `ds-license`.
> Add client generation

- conf/ds-storage-behaviour.yaml
- conf/ds-storage.logback.xml
- src/main/java/dk/kb/storage/config/ServiceConfig.java
This pull request aligns deploy and logging with the rest of the ds-services and changes the "pvica.devel" to the new "ds.radiotv".
> Deploy and logging

- src/main/java/dk/kb/storage/api/v1/impl/DsStorageApiServiceImpl.java
- src/main/java/dk/kb/storage/facade/DsStorageFacade.java
- src/main/openapi/ds-storage-openapi_v1.yaml
- src/main/resources/DsStorageFacadeTest.java
- src/test/java/dk/kb/storage/facade/DsStorageFacadeTest.java
new:
1 openAPI method + 1 impl method +1 unittest.
> Disc 331 parent child part2

- src/main/openapi/ds-storage-openapi_v1.yaml
Update http return code as specified in DISC-318 and update some documentation
> Disc 318 update http status

- src/main/java/dk/kb/storage/api/v1/impl/DsStorageApiServiceImpl.java
- src/main/java/dk/kb/storage/facade/DsStorageFacade.java
- src/main/java/dk/kb/storage/storage/DsStorage.java
- src/main/openapi/ds-storage-openapi_v1.yaml
- src/test/java/dk/kb/storage/storage/DsStorageTest.java
YAML
API impl class
Facade
Storage
unittest
> deleteFromOrigin method implemented.

- src/main/java/dk/kb/storage/facade/DsStorageFacade.java
- src/main/java/dk/kb/storage/storage/DsStorage.java
- src/test/java/dk/kb/storage/facade/DsStorageFacadeTest.java
Minor hardening, little javadoc, some warn log
> Minor hardening, little javadoc, some warn log

- src/main/openapi/ds-storage-openapi_v1.yaml
Small pr adding examples to endpoints. Please check that the JSON keys in the examples are correct
> add example requests and responses

- pom.xml
- src/main/java/dk/kb/storage/webservice/ContextListener.java
- src/main/resources/logback.xml
Same as ds-license module.
Deployed to devel11 and working
> logback fix

- CHANGELOG.md
- pom.xml
- src/main/java/dk/kb/storage/api/v1/impl/DsStorageApiServiceImpl.java
- src/main/java/dk/kb/storage/facade/DsStorageFacade.java
- src/main/java/dk/kb/storage/util/DsStorageClient.java
- src/test/java/dk/kb/storage/util/DsStorageClientTest.java
Add Paging-Record-Count header to API endpoints that delivers multiple records.
> Disc 655 paging record count

- pom.xml
- src/main/openapi/ds-storage-openapi_v1.yaml
Opening as draft as there are multiple decisions to be made before this can be implemented correctly. 
Experimenting with injecting yaml into POM to then use it in OpenAPI specs. 
See internal issue for context
> Disc 637 adjust open api from config

- CHANGELOG.md
- src/main/java/dk/kb/storage/config/ServiceConfig.java
- src/test/java/dk/kb/storage/integration/DsStorageClientTest.java
- src/test/resources/.gitignore
Integration test uses aegis configuration.
And a little cleanup so integration test yaml file has same name as in other modules.
> Dra 103 unittest categories

- src/main/java/dk/kb/storage/api/v1/impl/DsStorageApiServiceImpl.java
- src/main/java/dk/kb/storage/facade/DsStorageFacade.java
- src/main/openapi/ds-storage-openapi_v1.yaml
- src/test/java/dk/kb/storage/facade/DsStorageFacadeTest.java
- src/test/java/dk/kb/storage/integration/DsStorageClientTest.java
4 API endpoint merged into 2. Code changes+unittest changes to reflect this change.
> Dra 107 storage better endpoint names

- CHANGELOG.md
- src/main/java/dk/kb/storage/api/v1/impl/DsStorageApiServiceImpl.java
- src/main/java/dk/kb/storage/facade/DsStorageFacade.java
- src/main/java/dk/kb/storage/storage/DsStorage.java
- src/main/openapi/ds-storage-openapi_v1.yaml
- src/test/java/dk/kb/storage/storage/DsStorageTest.java
- src/test/resources/ddl/create_ds_storage.ddl
- src/test/resources/ddl/create_ds_storage_h2_unittest.ddl
Added two new fields to record: kalturareferenceid and kalturainternalid. The kaltura internal id is required by the frontend for thumbnails and streaming. 
New service method to update the kalturaId for a record.
> Dra 314 kaltura

- src/main/java/dk/kb/storage/api/v1/impl/DsStorageApiServiceImpl.java
- src/main/java/dk/kb/storage/facade/DsStorageFacade.java
- src/main/java/dk/kb/storage/storage/DsStorage.java
- src/main/openapi/ds-storage-openapi_v1.yaml
- src/test/java/dk/kb/storage/facade/DsStorageFacadeTest.java
- src/test/java/dk/kb/storage/storage/DsStorageTest.java
- src/test/java/dk/kb/storage/storage/DsStorageUnitTestUtil.java
- src/test/resources/ddl/create_ds_storage.ddl
- src/test/resources/ddl/create_ds_storage_h2_unittest.ddl
Implementation to create/update/read the new mapping table that has two fields.
See jira for full description
> Dra 396 kaltura id mapping

- CHANGELOG.md
- conf/ds-storage-behaviour.yaml
- src/main/java/dk/kb/storage/config/ServiceConfig.java
- src/main/openapi/ds-storage-openapi_v1.yaml
- src/test/java/dk/kb/storage/facade/DsStorageFacadeTest.java
This pull request changes most multi-word configuration keys to camelCase.
No changes to `aegis` were needed.
> Switch config to camelCase

- CHANGELOG.md
- pom.xml
- src/main/java/dk/kb/storage/util/DsStorageClient.java
Fix client generation and change parent POM preparing for deployment to internal nexus
> Dra 590 move to internal nexus

- CHANGELOG.md
- src/main/java/dk/kb/storage/api/v1/impl/DsStorageApiServiceImpl.java
- src/main/java/dk/kb/storage/facade/DsStorageFacade.java
- src/main/java/dk/kb/storage/storage/DsStorage.java
- src/main/java/dk/kb/storage/util/DsStorageClient.java
- src/main/openapi/ds-storage-openapi_v1.yaml
- src/test/java/dk/kb/storage/storage/DsStorageTest.java
DRA-1135 add new method that only updates the referenceId field for a record
> DRA-1135 add new method that only updates the referenceId field for a record

- CHANGELOG.md
- conf/ds-storage-behaviour.yaml
- pom.xml
- src/main/java/dk/kb/storage/api/v1/impl/DsStorageApiServiceImpl.java
- src/main/java/dk/kb/storage/api/v1/impl/ServiceApiServiceImpl.java
- src/main/java/dk/kb/storage/webservice/KBAuthorization.java
- src/main/java/dk/kb/storage/webservice/KBAuthorizationInterceptor.java
- src/main/java/dk/kb/storage/webservice/KBOAuth2Handler.java
- src/main/openapi/ds-storage-openapi_v1.yaml
- src/main/templates/api.mustache
- src/main/templates/apiServiceImpl.mustache
Enable OAuth2 on module. No service methods are so far defined to require a token.
> Enable OAuth2 on module. 

- CHANGELOG.md
- conf/ds-storage-behaviour.yaml
- src/main/java/dk/kb/storage/config/ServiceConfig.java
- src/main/java/dk/kb/storage/storage/DsStorage.java
Extract connection pool size to property file.
Also changed property to total max connections and just not idle.
> Define connectionPoolSize in the propertyfile so it is not hardcoded.

- pom.xml
- src/main/java/dk/kb/storage/webservice/RedirectApiDocsServlet.java
- src/main/webapp/WEB-INF/web.xml
Add servlet to intercept requests to /api-docs and redirect to /api.
> Dra 282 correct api docs

- CHANGELOG.md
- pom.xml
- src/test/java/dk/kb/storage/integration/DsStorageClientTest.java
Added Oauth2 access token to integration-test service calls.
Remember to pull aegis and 'kb init'
> DRA-1763-ds-storage-oauth-integration-test
